### ISSUE TITLE
Typo in ParallelForEachAsync Parameter: maxDegreeOfParalellism

### ISSUE THREAD

**Issue by FacetiousProgrammer** [Dasync/AsyncEnumerable#19]
In AsyncEnumerable/src/Extensions/ParallelForEachExtensions.cs, the parameter name on some of the overloads is "maxDegreeOfParalellism" and should instead be spelled "maxDegreeOfParallelism".

**Comment by tyrotoxin** [comment]
That's a bad typo, agree, but that most likely will be changed with the next major release - otherwise simple parameter name change can be breaking when multiple assemblies in a solution use different versions of the same library.

**Comment by tyrotoxin** [comment]
@FacetiousProgrammer, this issue has been fixed in the latest version 3 of this library:
https://www.nuget.org/packages/AsyncEnumerator/3.0.0-beta1

As of now, it's marked as 'beta' since .NET Core 3.0 is still in preview. Otherwise, it's a properly working release.

Please note that there are other breaking changes - the library now replicates Microsoft's version of `IAsyncEnumerable` and `IAsyncEnumerator` interfaces.
