### ISSUE TITLE
What does 'unofficial predecessor version' mean

### ISSUE THREAD

**Issue by ndrwrbgs** [Dasync/AsyncEnumerable#26]
I presume this is because C#8 is planning to incorporate Async Streams. What do you see as the future of this library? Are the .NET team looking at this library for examples (e.g. authoring an enumerable is much easier here than in the System.Interactive namespace), do you expect this library to live alongside the BCL libraries, or do you expect them to supersede this and it to sunset when the Async Streams are officially released?

Thanks Serge!

**Comment by tyrotoxin** [comment]
hi @ndrwrbgs, this library was created before C# team announced a built-in language support for async enumerators in version 8.0 of the language (also known as 'Async Streams'). Then, the idea of this library was simply enable async enumerators in a similar way as you do regular enumerators. There is no connection between C# language team and this library (they might have looked at it, but honestly, I don't know). Hence you can call it an 'unofficial predecessor' of the feature.
When C# 8.0 is released, the library continue to exist. While you can easily upgrade your code to use built-in async enumerators due to similarity in syntax, all other useful extension methods might not be included in the next version of .NET (like `.Batch` or `.ParallelForEachAsync`). And not everyone will upgrade to C# 8.0 right away, so having an alternative for Async Streams will definitely take place for a couple of years.

**Comment by ndrwrbgs** [comment]
Thanks for the history! It sounds like when they finally finish up all of that stuff we should work to integrate into it as best as we can. Would making it so this library exposes `System.Collections.Generic.IAsyncEnumerable` from `System.Interactive.Async` make sense, providing translation functionality, or waiting until C#8 finalizes (and decides if they use that interface or another).
